[package]
name = "udp-dummy-server"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3.5.0"
kiwi-measurements = { workspace = true, default-features = false, features = [
    "serde",
] }
